name: Deploy Node.js/Vite app via SSH

on:
  push:
    branches: [ "main" ]  # Триггер на пуш в main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Укажи свою версию Node.js

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build  # Команда для сборки (должна создавать папку `dist`)

      - name: Install SSH key
        uses: Burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: ${{ secrets.REMOTE_PATH }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}